services:
  database1:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_DB: testdb
      PGDATA: /data/postgres
    ports:
      - 5438:5432
    volumes:
      - db1:/data/postgres
      - ./seed_scripts/00-create_tables.sql:/docker-entrypoint-initdb.d/00-create_tables.sql
      - ./seed_scripts/01-seed_data.sql:/docker-entrypoint-initdb.d/01-seed_data.sql
    networks:
      - db

  database2:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_DB: testdb
      PGDATA: /data/postgres
    ports:
      - 5437:5432
    volumes:
      - db2:/data/postgres
    networks:
      - db


networks:
  db:

volumes:
  db1:
  db2: